version: '3.9'

services:

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INIT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INIT_PASSWORD}
      
    volumes:
      - ./DatabaseInit.js:/docker-entrypoint-initdb.d/DatabaseInit.js:ro
